### ISSUE TITLE
Resize images inside message

### ISSUE THREAD

**Issue by GoczkuPL** [memeller/shrunked#12]
Hello!

Big thanks for Your work on this addon! It is possible to make auto resize images inside message? Now user can right click image inside message and choose "Resize this image". Nobody do this and some messages are really big.

Great job, greetings!

**Comment by GoczkuPL** [comment]
Hello, thanks for reply! I checked it. This notification is small, auto resize will be better if You can do this. Yes, it should work like for attachments, when sending e-mail, add-on window will appear. But there is something more which killing my mail server space. When somebody send us e-mail with images inside body and users answering or forwarding this message, there is no automatic resize. User can right-click on each image inside e-mail and resize manually. It is possible to add auto resize when answering/forwarding message? This will be a brilliant function!

Greetings!

**Comment by memeller** [comment]
> When somebody send us e-mail with images inside body and users answering or forwarding this message, there is no automatic resize.

This is indeed a huge problem for some emails, and a great idea to implement. I have created a separate issue so that #12 is only about the auto-resize option for new attachments/inline images.
