### ISSUE TITLE
INFO - HOW TO INSTALL

### ISSUE THREAD

**Issue by mrglutton** [memeller/shrunked#18]
### To install this plugin into your Thunderbird:

1. Download repository (as a zip)
2. unpack and **enter** plugin directory
3. Select **all files** and compress them to zip
4. Change extension to **.XPI**
5. Import into Thunderbird

**Done**

**Comment by memeller** [comment]
You do not need to download the whole repository, just head to [releases page](https://github.com/memeller/shrunked/releases), and download the latest xpi. If you are using firefox and the xpi file is not downloaded then you need to alt + left click on the xpi / right click and select "Save target as...".

**Comment by mrglutton** [comment]
I don't use GIT and couldn't find it. You should really put the info / link in readme file, because it was not straight forward.
