### ISSUE TITLE
large picture fails to resize

### ISSUE THREAD

**Issue by Tobi7241** [memeller/shrunked#29]
I try to add an large picture (jpg) 6951px x 4633px with file size 17MB and the extension only show "Dateigröße neu schätzen..."
I assume te scaling algorithm has internally run into error condition.

Any option to fix that ? how can I send you the failing image as testcase ?

**Comment by memeller** [comment]
Cannot reproduce, both algorithms work fine for a test image of 20000 x 11252 pixels:
![20000](https://github.com/memeller/shrunked/assets/1408352/e92e51db-16c9-49fe-9703-f53b0a083b5f)
Try other pictures to see if the problem is with your computer or with the picture.

**Comment by Tobi7241** [comment]
today I can confirm it's working. No idea what was the issue. Thanks for the quick response.
can be closed as no issue.
