### ISSUE TITLE
[FEATURE] heif reader support for TB on Mac

### ISSUE THREAD

**Issue by Tobi7241** [memeller/shrunked#30]
feature request to add heif picture support for Thunderbird on Mac.
Idea: add Nokiatech js heif reader to shrink native iPhone pictures from https://github.com/nokiatech/heif/tree/gh-pages/js

maybe just read heif and attach as shrunken jpg (aka "compatbility"..)?

**Comment by memeller** [comment]
I think heif support (viewing / converting) is a great idea for a standalone add-on, if someone is willing to make one. 
Personally, I think that any time a company creates a new format (for whatever reason), it is their responsibility to provide tools / libraries for reading/converting from the new format.
